# usb_cam_params.yaml
usb_cam:
  ros__parameters:
    video_device: "/dev/video3"
    image_width: 640
    image_height: 480
    pixel_format: "vuy422p"
    camera_frame_id: "usb_cam"
    io_method: "mmap"